import { EduApp, AppCategory, UserRole, EducationStage } from './types';

// Helper for all stages
const ALL_STAGES = [
  EducationStage.INFANTIL, 
  EducationStage.PRIMARIA, 
  EducationStage.SECUNDARIA, 
  EducationStage.BACHILLERATO, 
  EducationStage.FP, 
  EducationStage.UNIVERSIDAD
];

export const APP_DATA: EduApp[] = [
  {
    id: 'genially',
    name: 'Genially',
    description: { es: 'Plataforma para crear contenidos interactivos.', eu: 'Eduki interaktiboak sortzeko plataforma.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Freemium',
    website: 'https://genial.ly/es/',
    iconUrl: 'https://logo.clearbit.com/genial.ly',
    features: { es: ['Interactividad', 'Presentaciones', 'Gamificación'], eu: ['Interaktibitatea', 'Aurkezpenak', 'Gamifikazioa'] },
    minAge: 14
  },
  {
    id: 'educaplay',
    name: 'Educaplay',
    description: { es: 'Creación de actividades educativas multimedia.', eu: 'Multimedia jarduera hezigarriak sortzea.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.PRIMARIA],
    priceModel: 'Freemium',
    website: 'https://es.educaplay.com/',
    iconUrl: 'https://logo.clearbit.com/educaplay.com',
    features: { es: ['Crucigramas', 'Sopas de letras', 'Juegos'], eu: ['Gurutzegramak', 'Hizki-sopak', 'Jokoak'] },
    minAge: 14
  },
  {
    id: 'exelearning',
    name: 'eXeLearning',
    description: { es: 'Editor de recursos educativos interactivos de código abierto.', eu: 'Kode irekiko baliabide hezigarri interaktiboen editorea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Gratis',
    website: 'https://exelearning.net/',
    iconUrl: 'https://logo.clearbit.com/exelearning.net',
    features: { es: ['SCORM', 'Open Source', 'REA'], eu: ['SCORM', 'Kode Irekia', 'REA'] },
    minAge: 0
  },
  {
    id: 'liveworksheets',
    name: 'Liveworksheets',
    description: { es: 'Fichas interactivas autocorregibles.', eu: 'Fitxa interaktibo autozuzentzaileak.' },
    category: AppCategory.ASSESSMENT,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Freemium',
    website: 'https://www.liveworksheets.com/es',
    iconUrl: 'https://logo.clearbit.com/liveworksheets.com',
    features: { es: ['Fichas', 'Autocorrección', 'Digital'], eu: ['Fitxak', 'Autozuzenketa', 'Digitala'] },
    minAge: 18
  },
  {
    id: 'nearpod',
    name: 'Nearpod',
    description: { es: 'Lecciones interactivas y realidad virtual.', eu: 'Ikasgai interaktiboak eta errealitate birtuala.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Freemium',
    website: 'https://nearpod.com/',
    iconUrl: 'https://logo.clearbit.com/nearpod.com',
    features: { es: ['VR', 'Participación', 'Evaluación'], eu: ['VR', 'Partaidetza', 'Ebaluazioa'] },
    minAge: 14
  },
  {
    id: 'quizizz',
    name: 'Quizizz',
    description: { es: 'Cuestionarios gamificados para evaluación.', eu: 'Ebaluaziorako galdetegi gamifikatuak.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Freemium',
    website: 'https://quizizz.com/',
    iconUrl: 'https://logo.clearbit.com/quizizz.com',
    features: { es: ['Gamificación', 'Tests', 'Repaso'], eu: ['Gamifikazioa', 'Testak', 'Errepasoa'] },
    minAge: 14
  },
  {
    id: 'quizlet',
    name: 'Quizlet',
    description: { es: 'Tarjetas de aprendizaje y juegos de estudio.', eu: 'Ikasketa-txartelak eta ikasteko jokoak.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: ALL_STAGES,
    priceModel: 'Freemium',
    website: 'https://quizlet.com/es',
    iconUrl: 'https://logo.clearbit.com/quizlet.com',
    features: { es: ['Flashcards', 'Memoria', 'Idiomas'], eu: ['Flashcard-ak', 'Memoria', 'Hizkuntzak'] },
    minAge: 14
  },
  {
    id: 'wordwall',
    name: 'Wordwall',
    description: { es: 'Creación de recursos didácticos personalizados.', eu: 'Baliabide didaktiko pertsonalizatuak sortzea.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA],
    priceModel: 'Freemium',
    website: 'https://wordwall.net/es',
    iconUrl: 'https://logo.clearbit.com/wordwall.net',
    features: { es: ['Juegos', 'Plantillas', 'Interactivo'], eu: ['Jokoak', 'Txantiloiak', 'Interaktiboa'] },
    minAge: 14
  },
  {
    id: 'powtoon',
    name: 'Powtoon',
    description: { es: 'Software de animación para presentaciones.', eu: 'Aurkezpenetarako animazio softwarea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: ALL_STAGES,
    priceModel: 'Freemium',
    website: 'https://www.powtoon.com/',
    iconUrl: 'https://logo.clearbit.com/powtoon.com',
    features: { es: ['Video', 'Animación', 'Presentación'], eu: ['Bideoa', 'Animazioa', 'Aurkezpena'] },
    minAge: 14
  },
  {
    id: 'geogebra',
    name: 'GeoGebra',
    description: { es: 'Matemáticas dinámicas para todos los niveles.', eu: 'Maila guztietarako matematika dinamikoa.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Gratis',
    website: 'https://www.geogebra.org/',
    iconUrl: 'https://logo.clearbit.com/geogebra.org',
    features: { es: ['Geometría', 'Álgebra', 'STEM'], eu: ['Geometria', 'Aljebra', 'STEM'] },
    minAge: 14
  },
  {
    id: 'sandbox',
    name: 'Sandbox Educación',
    description: { es: 'Entorno de simulación y experimentación virtual.', eu: 'Simulazio eta esperimentazio birtualeko ingurunea.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.INFANTIL, EducationStage.PRIMARIA],
    priceModel: 'Gratis',
    website: 'https://sandboxeducacion.es/',
    iconUrl: 'https://logo.clearbit.com/sandboxeducacion.es',
    features: { es: ['Simulación', 'Juego', 'Virtual'], eu: ['Simulazioa', 'Jokoa', 'Birtuala'] },
    minAge: 0
  },
  {
    id: 'lumi',
    name: 'Lumi',
    description: { es: 'Editor de escritorio para contenido H5P.', eu: 'H5P edukietarako mahaigaineko editorea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://app.lumi.education/',
    iconUrl: 'https://logo.clearbit.com/lumi.education',
    features: { es: ['H5P', 'Interactivo', 'Offline'], eu: ['H5P', 'Interaktiboa', 'Offline'] },
    minAge: 0
  },
  {
    id: 'decktoys',
    name: 'Deck.Toys',
    description: { es: 'Creación de lecciones como itinerarios de aventura.', eu: 'Abentura-ibilbide moduko ikasgaiak sortzea.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA],
    priceModel: 'Freemium',
    website: 'https://deck.toys/',
    iconUrl: 'https://logo.clearbit.com/deck.toys',
    features: { es: ['Gamificación', 'Itinerarios', 'Aventura'], eu: ['Gamifikazioa', 'Ibilbideak', 'Abentura'] },
    minAge: 18
  },
  {
    id: 'lucidchart',
    name: 'Lucidchart',
    description: { es: 'Diagramas y mapas mentales colaborativos.', eu: 'Diagrama eta mapa mental kolaboratiboak.' },
    category: AppCategory.COLLABORATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Freemium',
    website: 'https://www.lucidchart.com/pages/es',
    iconUrl: 'https://logo.clearbit.com/lucidchart.com',
    features: { es: ['Diagramas', 'Colaboración', 'Visual'], eu: ['Diagramak', 'Lankidetza', 'Bisuala'] },
    minAge: 14
  },
  {
    id: 'drawio',
    name: 'Draw.io',
    description: { es: 'Software de diagramación gratuito.', eu: 'Doako diagramazio softwarea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Gratis',
    website: 'https://www.drawio.com/',
    iconUrl: 'https://logo.clearbit.com/draw.io',
    features: { es: ['Diagramas', 'Open Source', 'Esquemas'], eu: ['Diagramak', 'Kode Irekia', 'Eskemak'] },
    minAge: 0
  },
  {
    id: 'mindomo',
    name: 'Mindomo',
    description: { es: 'Mapas mentales y conceptuales.', eu: 'Mapa mental eta kontzeptualak.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Freemium',
    website: 'https://www.mindomo.com/es/',
    iconUrl: 'https://logo.clearbit.com/mindomo.com',
    features: { es: ['Mapas Mentales', 'Esquemas', 'Estudio'], eu: ['Mapa Mentalak', 'Eskemak', 'Ikasketa'] },
    minAge: 0
  },
  {
    id: 'wevideo',
    name: 'WeVideo',
    description: { es: 'Edición de video en la nube.', eu: 'Hodeiko bideo-edizioa.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Freemium',
    website: 'https://www.wevideo.com/',
    iconUrl: 'https://logo.clearbit.com/wevideo.com',
    features: { es: ['Video', 'Edición', 'Nube'], eu: ['Bideoa', 'Edizioa', 'Hodeia'] },
    minAge: 14
  },
  {
    id: 'googlevids',
    name: 'Google Vids',
    description: { es: 'Creación de video colaborativa de Google.', eu: 'Google-ren bideo-sorkuntza kolaboratiboa.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'https://workspace.google.com/intl/es/products/vids/',
    iconUrl: 'https://logo.clearbit.com/google.com',
    features: { es: ['Video', 'IA', 'Workspace'], eu: ['Bideoa', 'IA', 'Workspace'] },
    minAge: 0
  },
  {
    id: 'audacity',
    name: 'Audacity',
    description: { es: 'Grabación y edición de audio multipista.', eu: 'Pista anitzeko audio grabazioa eta edizioa.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'https://www.audacityteam.org/',
    iconUrl: 'https://logo.clearbit.com/audacityteam.org',
    features: { es: ['Audio', 'Edición', 'Open Source'], eu: ['Audioa', 'Edizioa', 'Kode Irekia'] },
    minAge: 0
  },
  {
    id: 'wavacity',
    name: 'Wavacity',
    description: { es: 'Clon web de Audacity.', eu: 'Audacity-ren web klona.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'https://wavacity.com/',
    iconUrl: 'https://logo.clearbit.com/wavacity.com',
    features: { es: ['Audio', 'Web', 'Edición'], eu: ['Audioa', 'Weba', 'Edizioa'] },
    minAge: 18
  },
  {
    id: 'twistedwave',
    name: 'TwistedWave',
    description: { es: 'Editor de audio online.', eu: 'Online audio editorea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Gratis',
    website: 'https://twistedwave.com/',
    iconUrl: 'https://logo.clearbit.com/twistedwave.com',
    features: { es: ['Audio', 'Nube', 'Rápido'], eu: ['Audioa', 'Hodeia', 'Azkarra'] },
    minAge: 18
  },
  {
    id: 'gcompris',
    name: 'GCompris',
    description: { es: 'Software educativo para niños de 2 a 10 años.', eu: '2-10 urteko haurrentzako hezkuntza-softwarea.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.INFANTIL, EducationStage.PRIMARIA],
    priceModel: 'Gratis',
    website: 'https://gcompris.net/',
    iconUrl: 'https://logo.clearbit.com/gcompris.net',
    features: { es: ['Juegos', 'Matemáticas', 'Lectura'], eu: ['Jokoak', 'Matematika', 'Irakurketa'] },
    minAge: 0
  },
  {
    id: 'bosque',
    name: 'Bosque de Fantasías',
    description: { es: 'Portal de cuentos y recursos educativos.', eu: 'Ipuin eta hezkuntza-baliabideen ataria.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.INFANTIL, EducationStage.PRIMARIA],
    priceModel: 'Gratis',
    website: 'https://www.bosquedefantasias.com/',
    iconUrl: 'https://logo.clearbit.com/bosquedefantasias.com',
    features: { es: ['Lectura', 'Cuentos', 'Infantil'], eu: ['Irakurketa', 'Ipuinak', 'Haurrak'] },
    minAge: 0
  },
  {
    id: 'cokitos',
    name: 'Cokitos',
    description: { es: 'Juegos educativos interactivos online.', eu: 'Online joko hezigarri interaktiboak.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.INFANTIL, EducationStage.PRIMARIA],
    priceModel: 'Gratis',
    website: 'https://www.cokitos.com/',
    iconUrl: 'https://logo.clearbit.com/cokitos.com',
    features: { es: ['Juegos', 'Online', 'Variedad'], eu: ['Jokoak', 'Online', 'Aniztasuna'] },
    minAge: 0
  },
  {
    id: 'cristic',
    name: 'Cristic',
    description: { es: 'Juegos educativos para infantil y primaria.', eu: 'Haur eta lehen hezkuntzako joko hezigarriak.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.INFANTIL, EducationStage.PRIMARIA],
    priceModel: 'Gratis',
    website: 'https://www.cristic.com/',
    iconUrl: 'https://logo.clearbit.com/cristic.com',
    features: { es: ['Juegos', 'Recursos', 'Gratis'], eu: ['Jokoak', 'Baliabideak', 'Doan'] },
    minAge: 0
  },
  {
    id: 'minecraft',
    name: 'Minecraft Education',
    description: { es: 'Aprendizaje basado en juegos y construcción.', eu: 'Jolasetan eta eraikuntzan oinarritutako ikaskuntza.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Pago',
    website: 'https://education.minecraft.net/es-es',
    iconUrl: 'https://logo.clearbit.com/minecraft.net',
    features: { es: ['Creatividad', 'Mundos 3D', 'Colaboración'], eu: ['Sormena', '3D Munduak', 'Lankidetza'] },
    minAge: 14
  },
  {
    id: 'meqr',
    name: 'Me-QR',
    description: { es: 'Generador de códigos QR.', eu: 'QR kode sortzailea.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.BOTH,
    stages: ALL_STAGES,
    priceModel: 'Freemium',
    website: 'https://me-qr.com/es',
    iconUrl: 'https://logo.clearbit.com/me-qr.com',
    features: { es: ['QR', 'Herramienta', 'Utilidad'], eu: ['QR', 'Tresna', 'Erabilgarritasuna'] },
    minAge: 0
  },
  {
    id: 'pixton',
    name: 'Pixton',
    description: { es: 'Creador de cómics para el aula.', eu: 'Gelarako komiki sortzailea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Freemium',
    website: 'https://www-es.pixton.com/',
    iconUrl: 'https://logo.clearbit.com/pixton.com',
    features: { es: ['Cómics', 'Narración', 'Creatividad'], eu: ['Komikiak', 'Narrazioa', 'Sormena'] },
    minAge: 18
  },
  {
    id: 'kahoot',
    name: 'Kahoot!',
    description: { es: 'Plataforma de aprendizaje basada en juegos.', eu: 'Jolasetan oinarritutako ikaskuntza plataforma.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Freemium',
    website: 'https://kahoot.com/',
    iconUrl: 'https://logo.clearbit.com/kahoot.com',
    features: { es: ['Quiz', 'Competición', 'Repaso'], eu: ['Galdetegia', 'Lehiaketa', 'Errepasoa'] },
    minAge: 14
  },
  {
    id: 'mentimeter',
    name: 'Mentimeter',
    description: { es: 'Presentaciones interactivas y encuestas.', eu: 'Aurkezpen interaktiboak eta inkestak.' },
    category: AppCategory.ASSESSMENT,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Freemium',
    website: 'https://www.mentimeter.com/es-ES',
    iconUrl: 'https://logo.clearbit.com/mentimeter.com',
    features: { es: ['Encuestas', 'Votación', 'Feedback'], eu: ['Inkestak', 'Bozketa', 'Feedback'] },
    minAge: 14
  },
  {
    id: 'plickers',
    name: 'Plickers',
    description: { es: 'Evaluación formativa sin dispositivos para alumnos.', eu: 'Gailurik gabeko ebaluazio formatiboa ikasleentzat.' },
    category: AppCategory.ASSESSMENT,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA],
    priceModel: 'Freemium',
    website: 'https://www.plickers.com/',
    iconUrl: 'https://logo.clearbit.com/plickers.com',
    features: { es: ['QR', 'Evaluación', 'Offline'], eu: ['QR', 'Ebaluazioa', 'Offline'] },
    minAge: 18
  },
  {
    id: 'socrative',
    name: 'Socrative',
    description: { es: 'Evaluación en tiempo real.', eu: 'Denbora errealeko ebaluazioa.' },
    category: AppCategory.ASSESSMENT,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Freemium',
    website: 'https://www.socrative.com/',
    iconUrl: 'https://logo.clearbit.com/socrative.com',
    features: { es: ['Quiz', 'Informes', 'Control'], eu: ['Galdetegia', 'Txostenak', 'Kontrola'] },
    minAge: 14
  },
  {
    id: 'pixlr',
    name: 'Pixlr',
    description: { es: 'Editor de fotos online.', eu: 'Online argazki editorea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Freemium',
    website: 'https://pixlr.com/es/',
    iconUrl: 'https://logo.clearbit.com/pixlr.com',
    features: { es: ['Imagen', 'Edición', 'Filtros'], eu: ['Irudia', 'Edizioa', 'Iragazkiak'] },
    minAge: 14
  },
  {
    id: 'befunky',
    name: 'BeFunky',
    description: { es: 'Plataforma creativa todo en uno.', eu: 'Dena-batean plataforma sortzailea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Freemium',
    website: 'https://www.befunky.com/',
    iconUrl: 'https://logo.clearbit.com/befunky.com',
    features: { es: ['Diseño', 'Collage', 'Fotos'], eu: ['Diseinua', 'Collage', 'Argazkiak'] },
    minAge: 0
  },
  {
    id: 'gimp',
    name: 'GIMP',
    description: { es: 'Editor de imágenes avanzado de código abierto.', eu: 'Kode irekiko irudi editore aurreratua.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'https://www.gimp.org/',
    iconUrl: 'https://logo.clearbit.com/gimp.org',
    features: { es: ['Diseño', 'Profesional', 'Software'], eu: ['Diseinua', 'Profesionala', 'Softwarea'] },
    minAge: 0
  },
  {
    id: 'krita',
    name: 'Krita',
    description: { es: 'Pintura digital e ilustración.', eu: 'Pintura digitala eta ilustrazioa.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'https://krita.org/es/',
    iconUrl: 'https://logo.clearbit.com/krita.org',
    features: { es: ['Dibujo', 'Arte', 'Digital'], eu: ['Marrazkia', 'Artea', 'Digitala'] },
    minAge: 0
  },
  {
    id: 'inkscape',
    name: 'Inkscape',
    description: { es: 'Editor de gráficos vectoriales.', eu: 'Bektore-grafikoen editorea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'https://inkscape.org/',
    iconUrl: 'https://logo.clearbit.com/inkscape.org',
    features: { es: ['Vectorial', 'Diseño', 'SVG'], eu: ['Bektoriala', 'Diseinua', 'SVG'] },
    minAge: 0
  },
  {
    id: 'canva',
    name: 'Canva',
    description: { es: 'Diseño gráfico simplificado.', eu: 'Diseinu grafiko sinplifikatua.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Freemium',
    website: 'https://www.canva.com/es_es/',
    iconUrl: 'https://logo.clearbit.com/canva.com',
    features: { es: ['Plantillas', 'Social', 'Visual'], eu: ['Txantiloiak', 'Soziala', 'Bisuala'] },
    minAge: 14
  },
  {
    id: 'adobeexpress',
    name: 'Adobe Express',
    description: { es: 'Creación de gráficos y videos web.', eu: 'Web grafiko eta bideoen sorkuntza.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Freemium',
    website: 'https://www.adobe.com/es/education/express/',
    iconUrl: 'https://logo.clearbit.com/adobe.com',
    features: { es: ['Adobe', 'Rápido', 'Calidad'], eu: ['Adobe', 'Azkarra', 'Kalitatea'] },
    minAge: 14
  },
  {
    id: 'flipboard',
    name: 'Flipboard',
    description: { es: 'Revista digital personalizada.', eu: 'Aldizkari digital pertsonalizatua.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'https://es-es.about.flipboard.com/',
    iconUrl: 'https://logo.clearbit.com/flipboard.com',
    features: { es: ['Noticias', 'Curación', 'Lectura'], eu: ['Albisteak', 'Komisariotza', 'Irakurketa'] },
    minAge: 14
  },
  {
    id: 'googlefonts',
    name: 'Google Fonts',
    description: { es: 'Biblioteca de fuentes tipográficas.', eu: 'Tipografia-iturrien liburutegia.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: ALL_STAGES,
    priceModel: 'Gratis',
    website: 'https://fonts.google.com/',
    iconUrl: 'https://logo.clearbit.com/fonts.google.com',
    features: { es: ['Fuentes', 'Diseño', 'Web'], eu: ['Iturriak', 'Diseinua', 'Weba'] },
    minAge: 0
  },
  {
    id: 'languagetool',
    name: 'LanguageTool',
    description: { es: 'Corrector gramatical y ortográfico.', eu: 'Gramatika eta ortografia zuzentzailea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: ALL_STAGES,
    priceModel: 'Gratis',
    website: 'https://languagetool.org/es',
    iconUrl: 'https://logo.clearbit.com/languagetool.org',
    features: { es: ['Escritura', 'Corrección', 'Idiomas'], eu: ['Idazketa', 'Zuzenketa', 'Hizkuntzak'] },
    minAge: 0
  },
  {
    id: 'katamotz',
    name: 'Katamotz',
    description: { es: 'Software para mejorar la lectura.', eu: 'Irakurketa hobetzeko softwarea.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://katamotz.net/',
    iconUrl: 'https://katamotz.net/wp-content/uploads/2016/06/cropped-logokata.png',
    features: { es: ['Lectura', 'Dislexia', 'Accesibilidad'], eu: ['Irakurketa', 'Dislexia', 'Irisgarritasuna'] },
    minAge: 0
  },
  {
    id: 'bookcreator',
    name: 'Book Creator',
    description: { es: 'Creación de libros digitales sencillos.', eu: 'Liburu digital errazak sortzea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Freemium',
    website: 'https://bookcreator.com/',
    iconUrl: 'https://logo.clearbit.com/bookcreator.com',
    features: { es: ['Libros', 'Digital', 'Creatividad'], eu: ['Liburuak', 'Digitala', 'Sormena'] },
    minAge: 14
  },
  {
    id: 'musiclab',
    name: 'Chrome Music Lab',
    description: { es: 'Experimentos musicales interactivos.', eu: 'Musika-esperimentu interaktiboak.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.INFANTIL, EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://musiclab.chromeexperiments.com/',
    iconUrl: 'https://logo.clearbit.com/musiclab.chromeexperiments.com',
    features: { es: ['Música', 'Sonido', 'Experimento'], eu: ['Musika', 'Soinua', 'Esperimentua'] },
    minAge: 0
  },
  {
    id: 'educima',
    name: 'Educima',
    description: { es: 'Generador de pasatiempos educativos.', eu: 'Denbora-pasa hezigarrien sortzailea.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://www.educima.com/',
    iconUrl: 'https://logo.clearbit.com/educima.com',
    features: { es: ['Crucigramas', 'Laberintos', 'Fichas'], eu: ['Gurutzegramak', 'Labirintoak', 'Fitxak'] },
    minAge: 0
  },
  {
    id: 'wordle',
    name: 'Wordle',
    description: { es: 'Juego de adivinar palabras.', eu: 'Hitzak asmatzeko jokoa.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://mywordle.strivemath.com/',
    iconUrl: 'https://logo.clearbit.com/nytimes.com',
    features: { es: ['Lógica', 'Palabras', 'Juego'], eu: ['Logika', 'Hitzak', 'Jokoa'] },
    minAge: 0
  },
  {
    id: 'excalidraw',
    name: 'Excalidraw',
    description: { es: 'Pizarra virtual estilo dibujo a mano.', eu: 'Esku-marrazki estiloko arbela birtuala.' },
    category: AppCategory.COLLABORATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Gratis',
    website: 'https://excalidraw.com/',
    iconUrl: 'https://logo.clearbit.com/excalidraw.com',
    features: { es: ['Dibujo', 'Pizarra', 'Sencillo'], eu: ['Marrazkia', 'Arbela', 'Erraza'] },
    minAge: 0
  },
  {
    id: 'figjam',
    name: 'FigJam',
    description: { es: 'Pizarra online para equipos.', eu: 'Taldeentzako online arbela.' },
    category: AppCategory.COLLABORATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Freemium',
    website: 'https://www.figma.com/figjam/',
    iconUrl: 'https://logo.clearbit.com/figma.com',
    features: { es: ['Lluvia de ideas', 'Notas', 'Diseño'], eu: ['Ideia-jasa', 'Oharrak', 'Diseinua'] },
    minAge: 14
  },
  {
    id: 'miro',
    name: 'Miro',
    description: { es: 'Plataforma visual colaborativa.', eu: 'Plataforma bisual kolaboratiboa.' },
    category: AppCategory.COLLABORATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Freemium',
    website: 'https://miro.com/es/',
    iconUrl: 'https://logo.clearbit.com/miro.com',
    features: { es: ['Gestión', 'Mapas', 'Agile'], eu: ['Kudeaketa', 'Mapak', 'Agile'] },
    minAge: 14
  },
  {
    id: 'openboard',
    name: 'OpenBoard',
    description: { es: 'Software de pizarra interactiva open source.', eu: 'Kode irekiko arbela interaktiboko softwarea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Gratis',
    website: 'https://openboard.ch/index.en.html',
    iconUrl: 'https://logo.clearbit.com/openboard.ch',
    features: { es: ['Pizarra', 'Escritorio', 'Educación'], eu: ['Arbela', 'Mahaigaina', 'Hezkuntza'] },
    minAge: 0
  },
  {
    id: 'procomun',
    name: 'Procomún',
    description: { es: 'Red de recursos educativos abiertos.', eu: 'Baliabide hezigarri irekien sarea.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Gratis',
    website: 'https://procomun.intef.es/',
    iconUrl: 'https://logo.clearbit.com/intef.es',
    features: { es: ['REA', 'Repositorio', 'INTEF'], eu: ['REA', 'Biltegia', 'INTEF'] },
    minAge: 0
  },
  {
    id: 'edpuzzle',
    name: 'Edpuzzle',
    description: { es: 'Convierte videos en lecciones.', eu: 'Bideoak ikasgai bihurtu.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Freemium',
    website: 'https://edpuzzle.com/',
    iconUrl: 'https://logo.clearbit.com/edpuzzle.com',
    features: { es: ['Video', 'Preguntas', 'Clase'], eu: ['Bideoa', 'Galderak', 'Klasea'] },
    minAge: 14
  },
  {
    id: 'cospaces',
    name: 'CoSpaces Edu',
    description: { es: 'Creación de VR y AR en el aula.', eu: 'VR eta AR sorkuntza gelan.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: ALL_STAGES,
    priceModel: 'Freemium',
    website: 'https://cospaces.io/edu/',
    iconUrl: 'https://logo.clearbit.com/cospaces.io',
    features: { es: ['3D', 'Realidad Virtual', 'Código'], eu: ['3D', 'Errealitate Birtuala', 'Kodea'] },
    minAge: 14
  },
  {
    id: 'additio',
    name: 'Additio',
    description: { es: 'Cuaderno digital del profesor.', eu: 'Irakaslearen koaderno digitala.' },
    category: AppCategory.MANAGEMENT,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Freemium',
    website: 'https://additioapp.com/',
    iconUrl: 'https://logo.clearbit.com/additioapp.com',
    features: { es: ['Evaluación', 'Notas', 'Planificación'], eu: ['Ebaluazioa', 'Oharrak', 'Plangintza'] },
    minAge: 18
  },
  {
    id: 'storyboardthat',
    name: 'Storyboard That',
    description: { es: 'Narración digital y guiones gráficos.', eu: 'Narrazio digitala eta gidoi grafikoak.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Freemium',
    website: 'https://www.storyboardthat.com/es',
    iconUrl: 'https://logo.clearbit.com/storyboardthat.com',
    features: { es: ['Historia', 'Visual', 'Escenas'], eu: ['Istorioa', 'Bisuala', 'Eszenak'] },
    minAge: 14
  },
  {
    id: 'formative',
    name: 'Formative',
    description: { es: 'Evaluación formativa en tiempo real.', eu: 'Denbora errealeko ebaluazio formatiboa.' },
    category: AppCategory.ASSESSMENT,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Freemium',
    website: 'https://www.formative.com/',
    iconUrl: 'https://logo.clearbit.com/formative.com',
    features: { es: ['Feedback', 'Respuestas', 'Clase'], eu: ['Feedback', 'Erantzunak', 'Klasea'] },
    minAge: 0
  },
  {
    id: 'microbit',
    name: 'Micro:bit',
    description: { es: 'Programación física y robótica.', eu: 'Programazio fisikoa eta robotika.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'https://microbit.org/',
    iconUrl: 'https://logo.clearbit.com/microbit.org',
    features: { es: ['Código', 'Hardware', 'STEM'], eu: ['Kodea', 'Hardware', 'STEM'] },
    minAge: 0
  },
  {
    id: 'mastodon',
    name: 'Mastodon',
    description: { es: 'Red social descentralizada.', eu: 'Sare sozial deszentralizatua.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'https://joinmastodon.org/es',
    iconUrl: 'https://logo.clearbit.com/joinmastodon.org',
    features: { es: ['Social', 'Privacidad', 'Fediverso'], eu: ['Soziala', 'Pribatutasuna', 'Fedibertsoa'] },
    minAge: 14
  },
  {
    id: 'tuxguitar',
    name: 'TuxGuitar',
    description: { es: 'Editor y reproductor de tablaturas multitrack.', eu: 'Pista anitzeko tablaturen editorea eta erreproduzitzailea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://sourceforge.net/projects/tuxguitar/',
    iconUrl: 'https://logo.clearbit.com/sourceforge.net',
    features: { es: ['Música', 'Tablatura', 'Open Source'], eu: ['Musika', 'Tablatura', 'Kode Irekia'] },
    minAge: 0
  },
  {
    id: 'jigsawplanet',
    name: 'Jigsaw Planet',
    description: { es: 'Puzles online gratuitos.', eu: 'Doako online puzleak.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.INFANTIL, EducationStage.PRIMARIA],
    priceModel: 'Gratis',
    website: 'https://www.jigsawplanet.com/',
    iconUrl: 'https://logo.clearbit.com/jigsawplanet.com',
    features: { es: ['Puzles', 'Juegos', 'Entretenimiento'], eu: ['Puzleak', 'Jokoak', 'Aisia'] },
    minAge: 18
  },
  {
    id: 'arasuite',
    name: 'AraSuite',
    description: { es: 'Herramientas de comunicación aumentativa.', eu: 'Komunikazio areagotuko tresnak.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://aulaabierta.arasaac.org/araword_inicio',
    iconUrl: 'https://logo.clearbit.com/arasaac.org',
    features: { es: ['Pictogramas', 'Accesibilidad', 'Comunicación'], eu: ['Piktogramak', 'Irisgarritasuna', 'Komunikazioa'] },
    minAge: 0
  },
  {
    id: 'pictotraductor',
    name: 'PictoTraductor',
    description: { es: 'Traducción a pictogramas.', eu: 'Piktogrametara itzultzea.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://www.pictotraductor.com/',
    iconUrl: 'https://logo.clearbit.com/pictotraductor.com',
    features: { es: ['Traducción', 'Visual', 'Inclusión'], eu: ['Itzulpena', 'Bisuala', 'Inklusioa'] },
    minAge: 0
  },
  {
    id: 'notebookcast',
    name: 'NotebookCast',
    description: { es: 'Pizarra blanca compartida en tiempo real.', eu: 'Denbora errealean partekatutako arbela zuria.' },
    category: AppCategory.COLLABORATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'https://www.notebookcast.com/es',
    iconUrl: 'https://logo.clearbit.com/notebookcast.com',
    features: { es: ['Pizarra', 'Online', 'Compartir'], eu: ['Arbela', 'Online', 'Partekatu'] },
    minAge: 0
  },
  {
    id: 'wbo',
    name: 'WBO',
    description: { es: 'Pizarra colaborativa minimalista.', eu: 'Arbela kolaboratibo minimalista.' },
    category: AppCategory.COLLABORATION,
    targetAudience: UserRole.STUDENT,
    stages: ALL_STAGES,
    priceModel: 'Gratis',
    website: 'https://wbo.ophir.dev/',
    iconUrl: 'https://wbo.ophir.dev/favicon.ico',
    features: { es: ['Simple', 'Dibujo', 'Web'], eu: ['Sinplea', 'Marrazkia', 'Weba'] },
    minAge: 0
  },
  {
    id: 'webwhiteboard',
    name: 'Web Whiteboard',
    description: { es: 'Pizarra online simple.', eu: 'Online arbela sinplea.' },
    category: AppCategory.COLLABORATION,
    targetAudience: UserRole.STUDENT,
    stages: ALL_STAGES,
    priceModel: 'Gratis',
    website: 'https://webwhiteboard.com/lite/',
    iconUrl: 'https://logo.clearbit.com/webwhiteboard.com',
    features: { es: ['Pizarra', 'Rápido', 'Sin registro'], eu: ['Arbela', 'Azkarra', 'Erregistrorik gabe'] },
    minAge: 0
  },
  {
    id: 'proyectoedia',
    name: 'Proyecto EDIA',
    description: { es: 'Recursos educativos abiertos (REA).', eu: 'Baliabide hezigarri irekiak (REA).' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Gratis',
    website: 'https://cedec.intef.es/recursos/',
    iconUrl: 'https://logo.clearbit.com/intef.es',
    features: { es: ['Recursos', 'Metodología', 'Proyectos'], eu: ['Baliabideak', 'Metodologia', 'Proiektuak'] },
    minAge: 0
  },
  {
    id: 'oercommons',
    name: 'OER Commons',
    description: { es: 'Biblioteca pública de recursos educativos abiertos.', eu: 'Baliabide hezigarri irekien liburutegi publikoa.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Gratis',
    website: 'https://oercommons.org/',
    iconUrl: 'https://logo.clearbit.com/oercommons.org',
    features: { es: ['Biblioteca', 'Internacional', 'REA'], eu: ['Liburutegia', 'Nazioartekoa', 'REA'] },
    minAge: 0
  },
  {
    id: 'flexbooks',
    name: 'FlexBooks',
    description: { es: 'Libros de texto digitales personalizables.', eu: 'Testuliburu digital pertsonalizagarriak.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://flexbooks.ck12.org/',
    iconUrl: 'https://logo.clearbit.com/ck12.org',
    features: { es: ['Libros', 'Ciencias', 'Matemáticas'], eu: ['Liburuak', 'Zientziak', 'Matematika'] },
    minAge: 0
  },
  {
    id: 'openstax',
    name: 'OpenStax',
    description: { es: 'Libros de texto gratuitos revisados por pares.', eu: 'Parekoek berrikusitako doako testuliburuak.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Gratis',
    website: 'https://openstax.org/k12',
    iconUrl: 'https://logo.clearbit.com/openstax.org',
    features: { es: ['Textos', 'Calidad', 'Universidad'], eu: ['Testuak', 'Kalitatea', 'Unibertsitatea'] },
    minAge: 0
  },
  {
    id: 'typingstudy',
    name: 'Typing Study',
    description: { es: 'Cursos de mecanografía gratis.', eu: 'Doako mekanografia ikastaroak.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://www.typingstudy.com/es',
    iconUrl: 'https://logo.clearbit.com/typingstudy.com',
    features: { es: ['Mecanografía', 'Teclado', 'Práctica'], eu: ['Mekanografia', 'Teklatua', 'Praktika'] },
    minAge: 18
  },
  {
    id: 'vedoque',
    name: 'Vedoque',
    description: { es: 'Juegos educativos y mecanografía.', eu: 'Joko hezigarriak eta mekanografia.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://www.vedoque.com/juegos/mecano/',
    iconUrl: 'https://logo.clearbit.com/vedoque.com',
    features: { es: ['Juegos', 'Infantil', 'Aprender'], eu: ['Jokoak', 'Haurrak', 'Ikasi'] },
    minAge: 0
  },
  {
    id: 'typingclub',
    name: 'TypingClub',
    description: { es: 'Aprende mecanografía online.', eu: 'Ikasi mekanografia online.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Gratis',
    website: 'https://www.typingclub.com/mecanografia',
    iconUrl: 'https://logo.clearbit.com/typingclub.com',
    features: { es: ['Lecciones', 'Progreso', 'Visual'], eu: ['Ikasgaiak', 'Aurrerapena', 'Bisuala'] },
    minAge: 18
  },
  {
    id: 'yenka',
    name: 'Yenka',
    description: { es: 'Simulación de laboratorios de ciencias y tecnología.', eu: 'Zientzia eta teknologia laborategien simulazioa.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Pago',
    website: 'https://yenka.com/yenka-espanol/',
    iconUrl: 'https://logo.clearbit.com/yenka.com',
    features: { es: ['Ciencia', 'Física', 'Química'], eu: ['Zientzia', 'Fisika', 'Kimika'] },
    minAge: 14
  },
  {
    id: 'texthelp',
    name: 'Texthelp',
    description: { es: 'Herramientas de alfabetización y accesibilidad.', eu: 'Alfabetatze eta irisgarritasun tresnak.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.STUDENT,
    stages: ALL_STAGES,
    priceModel: 'Pago',
    website: 'https://www.texthelp.com/',
    iconUrl: 'https://logo.clearbit.com/texthelp.com',
    features: { es: ['Lectura', 'Inclusión', 'Apoyo'], eu: ['Irakurketa', 'Inklusioa', 'Laguntza'] },
    minAge: 14
  },
  {
    id: 'tatum',
    name: 'Ta-tum',
    description: { es: 'Plataforma para el fomento de la lectura.', eu: 'Irakurketa sustatzeko plataforma.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA],
    priceModel: 'Pago',
    website: 'https://ta-tum.com/',
    iconUrl: 'https://logo.clearbit.com/ta-tum.com',
    features: { es: ['Libros', 'Gamificación', 'Detectives'], eu: ['Liburuak', 'Gamifikazioa', 'Detektibeak'] },
    minAge: 14
  },
  {
    id: 'intermatia',
    name: 'Intermatia',
    description: { es: 'Ejercicios de matemáticas interactivos.', eu: 'Matematika ariketa interaktiboak.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Pago',
    website: 'https://www.intermatia.com/',
    iconUrl: 'https://logo.clearbit.com/intermatia.com',
    features: { es: ['Matemáticas', 'Práctica', 'Nivel'], eu: ['Matematika', 'Praktika', 'Maila'] },
    minAge: 18
  },
  {
    id: 'monk',
    name: 'Monk',
    description: { es: 'Apoyo al aprendizaje de matemáticas.', eu: 'Matematika ikasteko laguntza.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.STUDENT,
    stages: [EducationStage.PRIMARIA],
    priceModel: 'Pago',
    website: 'https://monkedu.org/',
    iconUrl: 'https://logo.clearbit.com/monkedu.org',
    features: { es: ['Matemáticas', 'Primaria', 'Juego'], eu: ['Matematika', 'Lehen Hezkuntza', 'Jokoa'] },
    minAge: 14
  },
  {
    id: 'platinoeduca',
    name: 'Platino Educa',
    description: { es: 'Cine y educación.', eu: 'Zinema eta hezkuntza.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: ALL_STAGES,
    priceModel: 'Pago',
    website: 'https://www.platinoeduca.com/',
    iconUrl: 'https://logo.clearbit.com/platinoeduca.com',
    features: { es: ['Cine', 'Películas', 'Cultura'], eu: ['Zinema', 'Filmak', 'Kultura'] },
    minAge: 0
  },
  {
    id: 'smileandlearn',
    name: 'Smile and Learn',
    description: { es: 'Plataforma educativa 360º.', eu: '360º hezkuntza plataforma.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.INFANTIL, EducationStage.PRIMARIA],
    priceModel: 'Freemium',
    website: 'https://www.smileandlearn.com/',
    iconUrl: 'https://logo.clearbit.com/smileandlearn.com',
    features: { es: ['Cuentos', 'Juegos', 'Idiomas'], eu: ['Ipuinak', 'Jokoak', 'Hizkuntzak'] },
    minAge: 0
  },
  {
    id: 'twinkl',
    name: 'Twinkl',
    description: { es: 'Recursos docentes de alta calidad.', eu: 'Kalitate handiko irakasle baliabideak.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.INFANTIL, EducationStage.PRIMARIA],
    priceModel: 'Pago',
    website: 'https://www.twinkl.es/',
    iconUrl: 'https://logo.clearbit.com/twinkl.com',
    features: { es: ['Fichas', 'Decoración', 'Planeación'], eu: ['Fitxak', 'Dekorazioa', 'Plangintza'] },
    minAge: 0
  },
  {
    id: 'ororotv',
    name: 'Ororo.tv',
    description: { es: 'Aprende inglés viendo películas.', eu: 'Ikasi ingelesa filmak ikusiz.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: ALL_STAGES,
    priceModel: 'Freemium',
    website: 'https://ororo.tv/es',
    iconUrl: 'https://logo.clearbit.com/ororo.tv',
    features: { es: ['Video', 'Idiomas', 'Subtítulos'], eu: ['Bideoa', 'Hizkuntzak', 'Azpitituluak'] },
    minAge: 18
  },
  {
    id: 'eyeharp',
    name: 'EyeHarp',
    description: { es: 'Tocar música con la mirada.', eu: 'Musika begiradarekin jotzea.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.STUDENT,
    stages: ALL_STAGES,
    priceModel: 'Pago',
    website: 'https://eyeharp.org/',
    iconUrl: 'https://logo.clearbit.com/eyeharp.org',
    features: { es: ['Accesibilidad', 'Música', 'Inclusión'], eu: ['Irisgarritasuna', 'Musika', 'Inklusioa'] },
    minAge: 0
  },
  {
    id: 'grid3',
    name: 'Grid 3',
    description: { es: 'Software de comunicación aumentativa.', eu: 'Komunikazio areagotuko softwarea.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.STUDENT,
    stages: ALL_STAGES,
    priceModel: 'Pago',
    website: 'https://thinksmartbox.com/product/grid-3/',
    iconUrl: 'https://logo.clearbit.com/thinksmartbox.com',
    features: { es: ['Comunicación', 'Accesibilidad', 'Voz'], eu: ['Komunikazioa', 'Irisgarritasuna', 'Ahotsa'] },
    minAge: 0
  },
  {
    id: 'neuronup',
    name: 'NeuronUP',
    description: { es: 'Estimulación cognitiva.', eu: 'Estimulazio kognitiboa.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.BOTH,
    stages: ALL_STAGES,
    priceModel: 'Pago',
    website: 'https://neuronup.com/',
    iconUrl: 'https://logo.clearbit.com/neuronup.com',
    features: { es: ['Cognitivo', 'Rehabilitación', 'Ejercicios'], eu: ['Kognitiboa', 'Errehabilitazioa', 'Ariketak'] },
    minAge: 0
  },
  {
    id: 'max',
    name: 'Max (Cycling 74)',
    description: { es: 'Programación visual para música y media.', eu: 'Musika eta mediarako programazio bisuala.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP, EducationStage.UNIVERSIDAD],
    priceModel: 'Gratis',
    website: 'https://cycling74.com/',
    iconUrl: 'https://logo.clearbit.com/cycling74.com',
    features: { es: ['Programación', 'Audio', 'Interactivo'], eu: ['Programazioa', 'Audioa', 'Interaktiboa'] },
    minAge: 0
  },
  {
    id: 'sibelius',
    name: 'Sibelius',
    description: { es: 'Software de notación musical.', eu: 'Musika notazio softwarea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP, EducationStage.UNIVERSIDAD],
    priceModel: 'Pago',
    website: 'https://www.avid.com/sibelius',
    iconUrl: 'https://logo.clearbit.com/avid.com',
    features: { es: ['Partituras', 'Composición', 'Profesional'], eu: ['Partiturak', 'Konposizioa', 'Profesionala'] },
    minAge: 18
  },
  {
    id: 'studioone',
    name: 'Studio One',
    description: { es: 'DAW para producción musical.', eu: 'Musika ekoizpenerako DAW.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO, EducationStage.FP],
    priceModel: 'Pago',
    website: 'https://www.presonus.com/products/Studio-One',
    iconUrl: 'https://logo.clearbit.com/presonus.com',
    features: { es: ['Audio', 'Grabación', 'Mezcla'], eu: ['Audioa', 'Grabazioa', 'Nahasketa'] },
    minAge: 18
  },
  {
    id: 'pano2vr',
    name: 'Pano2VR',
    description: { es: 'Creación de tours virtuales.', eu: 'Bisita birtualak sortzea.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Pago',
    website: 'https://ggnome.com/pano2vr/',
    iconUrl: 'https://logo.clearbit.com/ggnome.com',
    features: { es: ['VR', 'Panoramas', '360'], eu: ['VR', 'Panoramak', '360'] },
    minAge: 18
  },
  {
    id: 'audioscore',
    name: 'AudioScore',
    description: { es: 'Transcripción de audio a partitura.', eu: 'Audiotik partiturarako transkripzioa.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.SECUNDARIA, EducationStage.FP],
    priceModel: 'Pago',
    website: 'https://www.neuratron.com/audioscore.htm',
    iconUrl: 'https://logo.clearbit.com/neuratron.com',
    features: { es: ['Música', 'Transcripción', 'IA'], eu: ['Musika', 'Transkripzioa', 'IA'] },
    minAge: 18
  },
  {
    id: 'noteperformer',
    name: 'NotePerformer',
    description: { es: 'Sonidos orquestales realistas con IA.', eu: 'IA bidezko orkestra soinu errealistak.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.SECUNDARIA, EducationStage.FP],
    priceModel: 'Pago',
    website: 'https://www.noteperformer.com/',
    iconUrl: 'https://logo.clearbit.com/noteperformer.com',
    features: { es: ['Orquesta', 'Sonido', 'Plugin'], eu: ['Orkestra', 'Soinua', 'Plugin'] },
    minAge: 18
  },
  {
    id: 'garritan',
    name: 'Garritan Personal Orchestra',
    description: { es: 'Librería de sonidos de orquesta.', eu: 'Orkestra soinuen liburutegia.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.SECUNDARIA, EducationStage.FP],
    priceModel: 'Pago',
    website: 'https://www.garritan.com/',
    iconUrl: 'https://logo.clearbit.com/garritan.com',
    features: { es: ['Música', 'Instrumentos', 'Calidad'], eu: ['Musika', 'Instrumentuak', 'Kalitatea'] },
    minAge: 0
  },
  {
    id: 'opa',
    name: 'Orchestra Play Along',
    description: { es: 'Práctica con acompañamiento orquestal.', eu: 'Orkestra laguntzarekin praktika.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.SECUNDARIA, EducationStage.FP],
    priceModel: 'Gratis',
    website: 'http://www.orchestraplayalong.org/',
    iconUrl: 'https://logo.clearbit.com/orchestraplayalong.org', // Placeholder or generic
    features: { es: ['Música', 'Práctica', 'Orquesta'], eu: ['Musika', 'Praktika', 'Orkestra'] },
    minAge: 0
  },
  {
    id: 'naxos',
    name: 'Naxos Music Library',
    description: { es: 'Biblioteca de música clásica en streaming.', eu: 'Musika klasikoaren streaming liburutegia.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Pago',
    website: 'https://www.naxosmusiclibrary.com/',
    iconUrl: 'https://logo.clearbit.com/naxosmusiclibrary.com',
    features: { es: ['Música Clásica', 'Streaming', 'Educación'], eu: ['Musika Klasikoa', 'Streaming', 'Hezkuntza'] },
    minAge: 18
  },
  {
    id: 'bandinabox',
    name: 'Band-in-a-Box',
    description: { es: 'Acompañamiento musical automático.', eu: 'Laguntza musikal automatikoa.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.SECUNDARIA, EducationStage.FP],
    priceModel: 'Pago',
    website: 'https://www.pgmusic.com/',
    iconUrl: 'https://logo.clearbit.com/pgmusic.com',
    features: { es: ['Acompañamiento', 'Jazz', 'Composición'], eu: ['Laguntza', 'Jazz', 'Konposizioa'] },
    minAge: 18
  },
  {
    id: 'epartitura',
    name: 'ePartitura',
    description: { es: 'Tienda y visor de partituras digitales.', eu: 'Partitura digitalen denda eta bisorea.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.BOTH,
    stages: ALL_STAGES,
    priceModel: 'Pago',
    website: 'https://epartitura.com/',
    iconUrl: 'https://logo.clearbit.com/epartitura.com',
    features: { es: ['Partituras', 'Digital', 'Música'], eu: ['Partiturak', 'Digitala', 'Musika'] },
    minAge: 0
  },
  {
    id: 'digitalconcerthall',
    name: 'Digital Concert Hall',
    description: { es: 'Conciertos de la Filarmónica de Berlín.', eu: 'Berlingo Filarmonikoaren kontzertuak.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Pago',
    website: 'https://www.digitalconcerthall.com/',
    iconUrl: 'https://logo.clearbit.com/digitalconcerthall.com',
    features: { es: ['Conciertos', 'Video', 'Clásica'], eu: ['Kontzertuak', 'Bideoa', 'Klasikoa'] },
    minAge: 18
  },
  {
    id: 'metopera',
    name: 'Met Opera on Demand',
    description: { es: 'Ópera en streaming.', eu: 'Opera streaming bidez.' },
    category: AppCategory.OTHER,
    targetAudience: UserRole.TEACHER,
    stages: ALL_STAGES,
    priceModel: 'Pago',
    website: 'https://www.metopera.org/',
    iconUrl: 'https://logo.clearbit.com/metopera.org',
    features: { es: ['Ópera', 'Arte', 'Streaming'], eu: ['Opera', 'Artea', 'Streaming'] },
    minAge: 18
  },
  {
    id: 'playlab',
    name: 'Playlab.ai',
    description: { es: 'Plataforma para crear herramientas de IA.', eu: 'IA tresnak sortzeko plataforma.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.TEACHER,
    stages: [EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Freemium',
    website: 'https://www.playlab.ai/',
    iconUrl: 'https://logo.clearbit.com/playlab.ai',
    features: { es: ['IA', 'Bots', 'Educación'], eu: ['IA', 'Bot-ak', 'Hezkuntza'] },
    minAge: 0
  },
  {
    id: 'educa360',
    name: 'Educa360',
    description: { es: 'Plataforma de realidad virtual educativa.', eu: 'Hezkuntza errealitate birtualeko plataforma.' },
    category: AppCategory.CONTENT_CREATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA, EducationStage.SECUNDARIA, EducationStage.BACHILLERATO],
    priceModel: 'Freemium',
    website: 'https://educa360.com/',
    iconUrl: 'https://logo.clearbit.com/educa360.com',
    features: { es: ['VR', 'Inmersivo', 'Aulas'], eu: ['VR', 'Murgiltzailea', 'Gelak'] },
    minAge: 0
  },
  {
    id: 'matific',
    name: 'Matific',
    description: { es: 'Matemáticas para primaria mediante juegos.', eu: 'Lehen hezkuntzako matematika jokoen bidez.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA],
    priceModel: 'Freemium',
    website: 'https://www.matific.com/es/es/home/',
    iconUrl: 'https://logo.clearbit.com/matific.com',
    features: { es: ['Matemáticas', 'Juego', 'K-6'], eu: ['Matematika', 'Jokoa', 'K-6'] },
    minAge: 0
  },
  {
    id: 'lumio',
    name: 'Lumio',
    description: { es: 'Aprendizaje colaborativo de SMART.', eu: 'SMART-en ikaskuntza kolaboratiboa.' },
    category: AppCategory.GAMIFICATION,
    targetAudience: UserRole.BOTH,
    stages: [EducationStage.PRIMARIA],
    priceModel: 'Freemium',
    website: 'https://www.smarttech.com/es-es/lumio',
    iconUrl: 'https://logo.clearbit.com/smarttech.com',
    features: { es: ['Interactivo', 'SMART', 'Clase'], eu: ['Interaktiboa', 'SMART', 'Klasea'] },
    minAge: 0
  }
];